# Generated by Django 2.1.12 on 2019-12-23 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('cat_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('cat_name', models.CharField(max_length=20)),
                ('agegroup', models.CharField(choices=[('kids', 'kids'), ('adults', 'adults')], max_length=2)),
                ('special_off', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('cid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=20)),
                ('contact', models.CharField(max_length=10)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='flipkart',
            fields=[
                ('fid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=25)),
                ('price', models.CharField(max_length=10)),
                ('discount', models.CharField(max_length=10)),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.category')),
            ],
        ),
        migrations.CreateModel(
            name='myntra',
            fields=[
                ('mid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=10)),
                ('discount', models.CharField(max_length=10)),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.category')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='fid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.flipkart'),
        ),
        migrations.AddField(
            model_name='customer',
            name='mid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.myntra'),
        ),
    ]
